#!/bin/bash

mkdir build
cd build

export LIBRARY_PATH=$PREFIX/lib
export INCLUDE_PATH=$PREFIX/include

export BLAS_DIR=$LIBRARY_PATH
export AMD_DIR=$SP_DIR/petsc
export UMFPACK_DIR=$SP_DIR/petsc

cmake .. \
  -DCMAKE_INSTALL_PREFIX=$PREFIX \
  -DCMAKE_INCLUDE_PATH=$INCLUDE_PATH \
  -DCMAKE_LIBRARY_PATH=$LIBRARY_PATH \
  -DMPI_C_LIBRARIES=$LIBRARY_PATH \
  -DMPI_C_INCLUDE_PATH=$INCLUDE_PATH \
  -DMPI_CXX_LIBRARIES=$LIBRARY_PATH \
  -DMPI_CXX_INCLUDE_PATH=$INCLUDE_PATH \
  -DMPI_Fortran_LIBRARIES=$LIBRARY_PATH \
  -DMPI_Fortran_INCLUDE_PATH=$INCLUDE_PATH
make install
